package com.example.kotlinchallenge

import java.util.*
import kotlin.collections.ArrayList

class Main {
    val units: ArrayList<String> = arrayListOf(
        "One", "Two", "Three", "Four", "Five", "Six",
        "Seven", "Eight", "Nine"
    )

    val teens: ArrayList<String> = arrayListOf(
        "Eleven", "Twelve", "Thirteen", "Fourteen",
        "Fifteen", "Sixteen", "Seventeen", "Eighteen", "Nineteen"
    )

    val tens: ArrayList<String> = arrayListOf(
        "Ten", "Twenty", "Thirty", "Forty", "Fifty",
        "Sixty", "Seventy", "Eighty", "Ninety"
    )
    val hundreds: ArrayList<String> = arrayListOf(
        "One Hundred ", "Two hundred", "Three Hundred",
        "Four hundred", "Five hundred", "Six hundred", "Seven Hundred", "Eight hundred",
        "Nine hundred"
    )
    val thousand: ArrayList<String> = arrayListOf("One Thousand")


    fun main(args: Array<String>) {
        
        // Provide a Long argument between 1 and 1000 ONLY
        numberToString(135)
    }


    fun numberToString(number: Long): String {
        var num = number.toString()

        if (num.length == 1) {
            when (num) {
                "1" -> return units[0]
                "2" -> return units[1]
                "3" -> return units[2]
                "4" -> return units[3]
                "5" -> return units[4]
                "6" -> return units[5]
                "7" -> return units[6]
                "8" -> return units[7]
                "9" -> return units[8]
            }

        } else if ((num.length == 2) && (num[0] == '1')) {
            when (num) {
                "10" -> return tens[0]
                "11" -> return teens[0]
                "12" -> return teens[1]
                "13" -> return teens[2]
                "14" -> return teens[3]
                "15" -> return teens[4]
                "16" -> return teens[5]
                "17" -> return teens[6]
                "18" -> return teens[7]
                "19" -> return teens[8]
            }
        } else if ((num.length == 2) && (num[0] == '2')) {
            when (num) {
                "20" -> return tens[1]
                "21" -> return tens[1] + units[0]
                "22" -> return tens[1] + units[1]
                "23" -> return tens[1] + units[2]
                "24" -> return tens[1] + units[3]
                "25" -> return tens[1] + units[4]
                "26" -> return tens[1] + units[5]
                "27" -> return tens[1] + units[6]
                "28" -> return tens[1] + units[7]
                "29" -> return tens[1] + units[8]
            }
        } else if ((num.length == 2) && (num[0] == '3')) {
            when (num) {
                "30" -> return tens[2]
                "31" -> return tens[2] + units[0]
                "32" -> return tens[2] + units[1]
                "33" -> return tens[2] + units[2]
                "34" -> return tens[2] + units[3]
                "35" -> return tens[2] + units[4]
                "36" -> return tens[2] + units[5]
                "37" -> return tens[2] + units[6]
                "38" -> return tens[2] + units[7]
                "39" -> return tens[2] + units[8]
            }
        } else if ((num.length == 2) && (num[0] == '4')) {
            when (num) {
                "40" -> return tens[3]
                "41" -> return tens[3] + units[0]
                "42" -> return tens[3] + units[1]
                "43" -> return tens[3] + units[2]
                "44" -> return tens[3] + units[3]
                "45" -> return tens[3] + units[4]
                "46" -> return tens[3] + units[5]
                "47" -> return tens[3] + units[6]
                "48" -> return tens[3] + units[7]
                "49" -> return tens[3] + units[8]
            }
        } else if ((num.length == 2) && (num[0] == '5')) {
            when (num) {
                "50" -> return tens[4]
                "51" -> return tens[4] + units[0]
                "52" -> return tens[4] + units[1]
                "53" -> return tens[4] + units[2]
                "54" -> return tens[4] + units[3]
                "55" -> return tens[4] + units[4]
                "56" -> return tens[4] + units[5]
                "57" -> return tens[4] + units[6]
                "58" -> return tens[4] + units[7]
                "59" -> return tens[4] + units[8]
            }

        } else if ((num.length == 2) && (num[0] == '6')) {
            when (num) {
                "60" -> return tens[5]
                "61" -> return tens[5] + units[0]
                "62" -> return tens[5] + units[1]
                "63" -> return tens[5] + units[2]
                "64" -> return tens[5] + units[3]
                "65" -> return tens[5] + units[4]
                "66" -> return tens[5] + units[5]
                "67" -> return tens[5] + units[6]
                "68" -> return tens[5] + units[7]
                "69" -> return tens[5] + units[8]
            }
        } else if ((num.length == 2) && (num[0] == '7')) {
            when (num) {
                "70" -> return tens[6]
                "71" -> return tens[6] + units[0]
                "72" -> return tens[6] + units[1]
                "73" -> return tens[6] + units[2]
                "74" -> return tens[6] + units[3]
                "75" -> return tens[6] + units[4]
                "76" -> return tens[6] + units[5]
                "77" -> return tens[6] + units[6]
                "78" -> return tens[6] + units[7]
                "79" -> return tens[6] + units[8]
            }
        } else if ((num.length == 2) && (num[0] == '8')) {
            when (num) {
                "80" -> return tens[7]
                "81" -> return tens[7] + units[0]
                "82" -> return tens[7] + units[1]
                "83" -> return tens[7] + units[2]
                "84" -> return tens[7] + units[3]
                "85" -> return tens[7] + units[4]
                "86" -> return tens[7] + units[5]
                "87" -> return tens[7] + units[6]
                "88" -> return tens[7] + units[7]
                "89" -> return tens[7] + units[8]
            }
        } else if ((num.length == 2) && (num[0] == '9')) {
            when (num) {
                "90" -> return tens[8]
                "91" -> return tens[8] + units[0]
                "92" -> return tens[8] + units[1]
                "93" -> return tens[8] + units[2]
                "94" -> return tens[8] + units[3]
                "95" -> return tens[8] + units[4]
                "96" -> return tens[8] + units[5]
                "97" -> return tens[8] + units[6]
                "98" -> return tens[8] + units[7]
                "99" -> return tens[8] + units[8]
            }
        } else if ((num.length == 3) && (num[1] == '1')) {
            when (num) {
                "100" -> return hundreds[0]
                "101" -> return hundreds[0] + " and " + units[0]
                "102" -> return hundreds[0] + " and " + units[1]
                "103" -> return hundreds[0] + " and " + units[2]
                "104" -> return hundreds[0] + " and " + units[3]
                "105" -> return hundreds[0] + " and " + units[4]
                "106" -> return hundreds[0] + " and " + units[5]
                "107" -> return hundreds[0] + " and " + units[6]
                "108" -> return hundreds[0] + " and " + units[7]
                "109" -> return hundreds[0] + " and " + units[8]
                "110" -> return hundreds[0] + " and " + tens[0]
                "111" -> return hundreds[0] + " and " + teens[0]
                "112" -> return hundreds[0] + " and " + teens[1]
                "113" -> return hundreds[0] + " and " + teens[2]
                "114" -> return hundreds[0] + " and " + teens[3]
                "115" -> return hundreds[0] + " and " + teens[4]
                "116" -> return hundreds[0] + " and " + teens[5]
                "117" -> return hundreds[0] + " and " + teens[6]
                "118" -> return hundreds[0] + " and " + teens[7]
                "119" -> return hundreds[0] + " and " + teens[8]
                "120" -> return hundreds[0] + " and " + tens[1]
                "121" -> return hundreds[0] + " and " + tens[1] + units[0]
                "122" -> return hundreds[0] + " and " + tens[1] + units[1]
                "123" -> return hundreds[0] + " and " + tens[1] + units[2]
                "124" -> return hundreds[0] + " and " + tens[1] + units[3]
                "125" -> return hundreds[0] + " and " + tens[1] + units[4]
                "126" -> return hundreds[0] + " and " + tens[1] + units[5]
                "127" -> return hundreds[0] + " and " + tens[1] + units[6]
                "128" -> return hundreds[0] + " and " + tens[1] + units[7]
                "129" -> return hundreds[0] + " and " + tens[1] + units[8]
                "130" -> return hundreds[0] + " and " + tens[2]
                "131" -> return hundreds[0] + " and " + tens[2] + units[0]
                "132" -> return hundreds[0] + " and " + tens[2] + units[1]
                "133" -> return hundreds[0] + " and " + tens[2] + units[2]
                "134" -> return hundreds[0] + " and " + tens[2] + units[3]
                "135" -> return hundreds[0] + " and " + tens[2] + units[4]
                "136" -> return hundreds[0] + " and " + tens[2] + units[5]
                "137" -> return hundreds[0] + " and " + tens[2] + units[6]
                "138" -> return hundreds[0] + " and " + tens[2] + units[7]
                "139" -> return hundreds[0] + " and " + tens[2] + units[8]
                "140" -> return hundreds[0] + " and " + tens[3]
                "141" -> return hundreds[0] + " and " + tens[3] + units[0]
                "142" -> return hundreds[0] + " and " + tens[3] + units[1]
                "143" -> return hundreds[0] + " and " + tens[3] + units[2]
                "144" -> return hundreds[0] + " and " + tens[3] + units[3]
                "145" -> return hundreds[0] + " and " + tens[3] + units[4]
                "146" -> return hundreds[0] + " and " + tens[3] + units[5]
                "147" -> return hundreds[0] + " and " + tens[3] + units[6]
                "148" -> return hundreds[0] + " and " + tens[3] + units[7]
                "149" -> return hundreds[0] + " and " + tens[3] + units[8]
                "150" -> return hundreds[0] + " and " + tens[4]
                "151" -> return hundreds[0] + " and " + tens[4] + units[0]
                "152" -> return hundreds[0] + " and " + tens[4] + units[1]
                "153" -> return hundreds[0] + " and " + tens[4] + units[2]
                "154" -> return hundreds[0] + " and " + tens[4] + units[3]
                "155" -> return hundreds[0] + " and " + tens[4] + units[4]
                "156" -> return hundreds[0] + " and " + tens[4] + units[5]
                "157" -> return hundreds[0] + " and " + tens[4] + units[6]
                "158" -> return hundreds[0] + " and " + tens[4] + units[7]
                "159" -> return hundreds[0] + " and " + tens[4] + units[8]
                "160" -> return hundreds[0] + " and " + tens[5]
                "161" -> return hundreds[0] + " and " + tens[5] + units[0]
                "162" -> return hundreds[0] + " and " + tens[5] + units[1]
                "163" -> return hundreds[0] + " and " + tens[5] + units[2]
                "164" -> return hundreds[0] + " and " + tens[5] + units[3]
                "165" -> return hundreds[0] + " and " + tens[5] + units[4]
                "166" -> return hundreds[0] + " and " + tens[5] + units[5]
                "167" -> return hundreds[0] + " and " + tens[5] + units[6]
                "168" -> return hundreds[0] + " and " + tens[5] + units[7]
                "169" -> return hundreds[0] + " and " + tens[5] + units[8]
                "170" -> return hundreds[0] + " and " + tens[6]
                "171" -> return hundreds[0] + " and " + tens[6] + units[0]
                "172" -> return hundreds[0] + " and " + tens[6] + units[1]
                "173" -> return hundreds[0] + " and " + tens[6] + units[2]
                "174" -> return hundreds[0] + " and " + tens[6] + units[3]
                "175" -> return hundreds[0] + " and " + tens[6] + units[4]
                "176" -> return hundreds[0] + " and " + tens[6] + units[5]
                "177" -> return hundreds[0] + " and " + tens[6] + units[6]
                "178" -> return hundreds[0] + " and " + tens[6] + units[7]
                "179" -> return hundreds[0] + " and " + tens[6] + units[8]
                "180" -> return hundreds[0] + " and " + tens[7]
                "181" -> return hundreds[0] + " and " + tens[7] + units[0]
                "182" -> return hundreds[0] + " and " + tens[7] + units[1]
                "183" -> return hundreds[0] + " and " + tens[7] + units[2]
                "184" -> return hundreds[0] + " and " + tens[7] + units[3]
                "185" -> return hundreds[0] + " and " + tens[7] + units[4]
                "186" -> return hundreds[0] + " and " + tens[7] + units[5]
                "187" -> return hundreds[0] + " and " + tens[7] + units[6]
                "188" -> return hundreds[0] + " and " + tens[7] + units[7]
                "189" -> return hundreds[0] + " and " + tens[7] + units[8]
                "190" -> return hundreds[0] + " and " + tens[8]
                "191" -> return hundreds[0] + " and " + tens[8] + units[0]
                "192" -> return hundreds[0] + " and " + tens[8] + units[1]
                "193" -> return hundreds[0] + " and " + tens[8] + units[2]
                "194" -> return hundreds[0] + " and " + tens[8] + units[3]
                "195" -> return hundreds[0] + " and " + tens[8] + units[4]
                "196" -> return hundreds[0] + " and " + tens[8] + units[5]
                "197" -> return hundreds[0] + " and " + tens[8] + units[6]
                "198" -> return hundreds[0] + " and " + tens[8] + units[7]
                "199" -> return hundreds[0] + " and " + tens[8] + units[8]
            }
        } else if ((num.length == 3) && (num[1] == '2')) {
            when (num) {
                "200" -> return hundreds[1]
                "201" -> return hundreds[1] + " and " + units[0]
                "202" -> return hundreds[1] + " and " + units[1]
                "203" -> return hundreds[1] + " and " + units[2]
                "204" -> return hundreds[1] + " and " + units[3]
                "205" -> return hundreds[1] + " and " + units[4]
                "206" -> return hundreds[1] + " and " + units[5]
                "207" -> return hundreds[1] + " and " + units[6]
                "208" -> return hundreds[1] + " and " + units[7]
                "209" -> return hundreds[1] + " and " + units[8]
                "210" -> return hundreds[1] + " and " + tens[0]
                "211" -> return hundreds[1] + " and " + teens[0]
                "212" -> return hundreds[1] + " and " + teens[1]
                "213" -> return hundreds[1] + " and " + teens[2]
                "214" -> return hundreds[1] + " and " + teens[3]
                "215" -> return hundreds[1] + " and " + teens[4]
                "216" -> return hundreds[1] + " and " + teens[5]
                "217" -> return hundreds[1] + " and " + teens[6]
                "218" -> return hundreds[1] + " and " + teens[7]
                "219" -> return hundreds[1] + " and " + teens[8]
                "220" -> return hundreds[1] + " and " + tens[1]
                "221" -> return hundreds[1] + " and " + tens[1] + units[0]
                "222" -> return hundreds[1] + " and " + tens[1] + units[1]
                "223" -> return hundreds[1] + " and " + tens[1] + units[2]
                "224" -> return hundreds[1] + " and " + tens[1] + units[3]
                "225" -> return hundreds[1] + " and " + tens[1] + units[4]
                "226" -> return hundreds[1] + " and " + tens[1] + units[5]
                "227" -> return hundreds[1] + " and " + tens[1] + units[6]
                "228" -> return hundreds[1] + " and " + tens[1] + units[7]
                "229" -> return hundreds[1] + " and " + tens[1] + units[8]
                "230" -> return hundreds[1] + " and " + tens[2]
                "231" -> return hundreds[1] + " and " + tens[2] + units[0]
                "232" -> return hundreds[1] + " and " + tens[2] + units[1]
                "233" -> return hundreds[1] + " and " + tens[2] + units[2]
                "234" -> return hundreds[1] + " and " + tens[2] + units[3]
                "235" -> return hundreds[1] + " and " + tens[2] + units[4]
                "236" -> return hundreds[1] + " and " + tens[2] + units[5]
                "237" -> return hundreds[1] + " and " + tens[2] + units[6]
                "238" -> return hundreds[1] + " and " + tens[2] + units[7]
                "239" -> return hundreds[1] + " and " + tens[2] + units[8]
                "240" -> return hundreds[1] + " and " + tens[3]
                "241" -> return hundreds[1] + " and " + tens[3] + units[0]
                "242" -> return hundreds[1] + " and " + tens[3] + units[1]
                "243" -> return hundreds[1] + " and " + tens[3] + units[2]
                "244" -> return hundreds[1] + " and " + tens[3] + units[3]
                "245" -> return hundreds[1] + " and " + tens[3] + units[4]
                "246" -> return hundreds[1] + " and " + tens[3] + units[5]
                "247" -> return hundreds[1] + " and " + tens[3] + units[6]
                "248" -> return hundreds[1] + " and " + tens[3] + units[7]
                "249" -> return hundreds[1] + " and " + tens[3] + units[8]
                "250" -> return hundreds[1] + " and " + tens[4]
                "251" -> return hundreds[1] + " and " + tens[4] + units[0]
                "252" -> return hundreds[1] + " and " + tens[4] + units[1]
                "253" -> return hundreds[1] + " and " + tens[4] + units[2]
                "254" -> return hundreds[1] + " and " + tens[4] + units[3]
                "255" -> return hundreds[1] + " and " + tens[4] + units[4]
                "256" -> return hundreds[1] + " and " + tens[4] + units[5]
                "257" -> return hundreds[1] + " and " + tens[4] + units[6]
                "258" -> return hundreds[1] + " and " + tens[4] + units[7]
                "259" -> return hundreds[1] + " and " + tens[4] + units[8]
                "260" -> return hundreds[1] + " and " + tens[5]
                "261" -> return hundreds[1] + " and " + tens[5] + units[0]
                "262" -> return hundreds[1] + " and " + tens[5] + units[1]
                "263" -> return hundreds[1] + " and " + tens[5] + units[2]
                "264" -> return hundreds[1] + " and " + tens[5] + units[3]
                "265" -> return hundreds[1] + " and " + tens[5] + units[4]
                "266" -> return hundreds[1] + " and " + tens[5] + units[5]
                "267" -> return hundreds[1] + " and " + tens[5] + units[6]
                "268" -> return hundreds[1] + " and " + tens[5] + units[7]
                "269" -> return hundreds[1] + " and " + tens[5] + units[8]
                "270" -> return hundreds[1] + " and " + tens[6]
                "271" -> return hundreds[1] + " and " + tens[6] + units[0]
                "272" -> return hundreds[1] + " and " + tens[6] + units[1]
                "273" -> return hundreds[1] + " and " + tens[6] + units[2]
                "274" -> return hundreds[1] + " and " + tens[6] + units[3]
                "275" -> return hundreds[1] + " and " + tens[6] + units[4]
                "276" -> return hundreds[1] + " and " + tens[6] + units[5]
                "277" -> return hundreds[1] + " and " + tens[6] + units[6]
                "278" -> return hundreds[1] + " and " + tens[6] + units[7]
                "279" -> return hundreds[1] + " and " + tens[6] + units[8]
                "280" -> return hundreds[1] + " and " + tens[7]
                "281" -> return hundreds[1] + " and " + tens[7] + units[0]
                "282" -> return hundreds[1] + " and " + tens[7] + units[1]
                "283" -> return hundreds[1] + " and " + tens[7] + units[2]
                "284" -> return hundreds[1] + " and " + tens[7] + units[3]
                "285" -> return hundreds[1] + " and " + tens[7] + units[4]
                "286" -> return hundreds[1] + " and " + tens[7] + units[5]
                "287" -> return hundreds[1] + " and " + tens[7] + units[6]
                "288" -> return hundreds[1] + " and " + tens[7] + units[7]
                "289" -> return hundreds[1] + " and " + tens[7] + units[8]
                "290" -> return hundreds[1] + " and " + tens[8]
                "291" -> return hundreds[1] + " and " + tens[8] + units[0]
                "292" -> return hundreds[1] + " and " + tens[8] + units[1]
                "293" -> return hundreds[1] + " and " + tens[8] + units[2]
                "294" -> return hundreds[1] + " and " + tens[8] + units[3]
                "295" -> return hundreds[1] + " and " + tens[8] + units[4]
                "296" -> return hundreds[1] + " and " + tens[8] + units[5]
                "297" -> return hundreds[1] + " and " + tens[8] + units[6]
                "298" -> return hundreds[1] + " and " + tens[8] + units[7]
                "299" -> return hundreds[1] + " and " + tens[8] + units[8]
            }
        } else if ((num.length == 3) && (num[1] == '3')) {
            when (num) {
                "300" -> return hundreds[2]
                "301" -> return hundreds[2] + " and " + units[0]
                "302" -> return hundreds[2] + " and " + units[1]
                "303" -> return hundreds[2] + " and " + units[2]
                "304" -> return hundreds[2] + " and " + units[3]
                "305" -> return hundreds[2] + " and " + units[4]
                "306" -> return hundreds[2] + " and " + units[5]
                "307" -> return hundreds[2] + " and " + units[6]
                "308" -> return hundreds[2] + " and " + units[7]
                "309" -> return hundreds[2] + " and " + units[8]
                "310" -> return hundreds[2] + " and " + tens[0]
                "311" -> return hundreds[2] + " and " + teens[0]
                "312" -> return hundreds[2] + " and " + teens[1]
                "313" -> return hundreds[2] + " and " + teens[2]
                "314" -> return hundreds[2] + " and " + teens[3]
                "315" -> return hundreds[2] + " and " + teens[4]
                "316" -> return hundreds[2] + " and " + teens[5]
                "317" -> return hundreds[2] + " and " + teens[6]
                "318" -> return hundreds[2] + " and " + teens[7]
                "319" -> return hundreds[2] + " and " + teens[8]
                "320" -> return hundreds[2] + " and " + tens[1]
                "321" -> return hundreds[2] + " and " + tens[1] + units[0]
                "322" -> return hundreds[2] + " and " + tens[1] + units[1]
                "323" -> return hundreds[2] + " and " + tens[1] + units[2]
                "324" -> return hundreds[2] + " and " + tens[1] + units[3]
                "325" -> return hundreds[2] + " and " + tens[1] + units[4]
                "326" -> return hundreds[2] + " and " + tens[1] + units[5]
                "327" -> return hundreds[2] + " and " + tens[1] + units[6]
                "328" -> return hundreds[2] + " and " + tens[1] + units[7]
                "329" -> return hundreds[2] + " and " + tens[1] + units[8]
                "330" -> return hundreds[2] + " and " + tens[2]
                "331" -> return hundreds[2] + " and " + tens[2] + units[0]
                "332" -> return hundreds[2] + " and " + tens[2] + units[1]
                "333" -> return hundreds[2] + " and " + tens[2] + units[2]
                "334" -> return hundreds[2] + " and " + tens[2] + units[3]
                "335" -> return hundreds[2] + " and " + tens[2] + units[4]
                "336" -> return hundreds[2] + " and " + tens[2] + units[5]
                "337" -> return hundreds[2] + " and " + tens[2] + units[6]
                "338" -> return hundreds[2] + " and " + tens[2] + units[7]
                "339" -> return hundreds[2] + " and " + tens[2] + units[8]
                "340" -> return hundreds[2] + " and " + tens[3]
                "341" -> return hundreds[2] + " and " + tens[3] + units[0]
                "342" -> return hundreds[2] + " and " + tens[3] + units[1]
                "343" -> return hundreds[2] + " and " + tens[3] + units[2]
                "344" -> return hundreds[2] + " and " + tens[3] + units[3]
                "345" -> return hundreds[2] + " and " + tens[3] + units[4]
                "346" -> return hundreds[2] + " and " + tens[3] + units[5]
                "347" -> return hundreds[2] + " and " + tens[3] + units[6]
                "348" -> return hundreds[2] + " and " + tens[3] + units[7]
                "349" -> return hundreds[2] + " and " + tens[3] + units[8]
                "350" -> return hundreds[2] + " and " + tens[4]
                "351" -> return hundreds[2] + " and " + tens[4] + units[0]
                "352" -> return hundreds[2] + " and " + tens[4] + units[1]
                "353" -> return hundreds[2] + " and " + tens[4] + units[2]
                "354" -> return hundreds[2] + " and " + tens[4] + units[3]
                "355" -> return hundreds[2] + " and " + tens[4] + units[4]
                "356" -> return hundreds[2] + " and " + tens[4] + units[5]
                "357" -> return hundreds[2] + " and " + tens[4] + units[6]
                "358" -> return hundreds[2] + " and " + tens[4] + units[7]
                "359" -> return hundreds[2] + " and " + tens[4] + units[8]
                "360" -> return hundreds[2] + " and " + tens[5]
                "361" -> return hundreds[2] + " and " + tens[5] + units[0]
                "362" -> return hundreds[2] + " and " + tens[5] + units[1]
                "363" -> return hundreds[2] + " and " + tens[5] + units[2]
                "364" -> return hundreds[2] + " and " + tens[5] + units[3]
                "365" -> return hundreds[2] + " and " + tens[5] + units[4]
                "366" -> return hundreds[2] + " and " + tens[5] + units[5]
                "367" -> return hundreds[2] + " and " + tens[5] + units[6]
                "368" -> return hundreds[2] + " and " + tens[5] + units[7]
                "369" -> return hundreds[2] + " and " + tens[5] + units[8]
                "370" -> return hundreds[2] + " and " + tens[6]
                "371" -> return hundreds[2] + " and " + tens[6] + units[0]
                "372" -> return hundreds[2] + " and " + tens[6] + units[1]
                "373" -> return hundreds[2] + " and " + tens[6] + units[2]
                "374" -> return hundreds[2] + " and " + tens[6] + units[3]
                "375" -> return hundreds[2] + " and " + tens[6] + units[4]
                "376" -> return hundreds[2] + " and " + tens[6] + units[5]
                "377" -> return hundreds[2] + " and " + tens[6] + units[6]
                "378" -> return hundreds[2] + " and " + tens[6] + units[7]
                "379" -> return hundreds[2] + " and " + tens[6] + units[8]
                "380" -> return hundreds[2] + " and " + tens[7]
                "381" -> return hundreds[2] + " and " + tens[7] + units[0]
                "382" -> return hundreds[2] + " and " + tens[7] + units[1]
                "383" -> return hundreds[2] + " and " + tens[7] + units[2]
                "384" -> return hundreds[2] + " and " + tens[7] + units[3]
                "385" -> return hundreds[2] + " and " + tens[7] + units[4]
                "386" -> return hundreds[2] + " and " + tens[7] + units[5]
                "387" -> return hundreds[2] + " and " + tens[7] + units[6]
                "388" -> return hundreds[2] + " and " + tens[7] + units[7]
                "389" -> return hundreds[2] + " and " + tens[7] + units[8]
                "390" -> return hundreds[2] + " and " + tens[8]
                "391" -> return hundreds[2] + " and " + tens[8] + units[0]
                "392" -> return hundreds[2] + " and " + tens[8] + units[1]
                "393" -> return hundreds[2] + " and " + tens[8] + units[2]
                "394" -> return hundreds[2] + " and " + tens[8] + units[3]
                "395" -> return hundreds[2] + " and " + tens[8] + units[4]
                "396" -> return hundreds[2] + " and " + tens[8] + units[5]
                "397" -> return hundreds[2] + " and " + tens[8] + units[6]
                "398" -> return hundreds[2] + " and " + tens[8] + units[7]
                "399" -> return hundreds[2] + " and " + tens[8] + units[8]
            }
        } else if ((num.length == 3) && (num[1] == '4')) {
            when (num) {
                "400" -> return hundreds[3]
                "401" -> return hundreds[3] + " and " + units[0]
                "402" -> return hundreds[3] + " and " + units[1]
                "403" -> return hundreds[3] + " and " + units[2]
                "404" -> return hundreds[3] + " and " + units[3]
                "405" -> return hundreds[3] + " and " + units[4]
                "406" -> return hundreds[3] + " and " + units[5]
                "407" -> return hundreds[3] + " and " + units[6]
                "408" -> return hundreds[3] + " and " + units[7]
                "409" -> return hundreds[3] + " and " + units[8]
                "410" -> return hundreds[3] + " and " + tens[0]
                "411" -> return hundreds[3] + " and " + teens[0]
                "412" -> return hundreds[3] + " and " + teens[1]
                "413" -> return hundreds[3] + " and " + teens[2]
                "414" -> return hundreds[3] + " and " + teens[3]
                "415" -> return hundreds[3] + " and " + teens[4]
                "416" -> return hundreds[3] + " and " + teens[5]
                "417" -> return hundreds[3] + " and " + teens[6]
                "418" -> return hundreds[3] + " and " + teens[7]
                "419" -> return hundreds[3] + " and " + teens[8]
                "420" -> return hundreds[3] + " and " + tens[1]
                "421" -> return hundreds[3] + " and " + tens[1] + units[0]
                "422" -> return hundreds[3] + " and " + tens[1] + units[1]
                "423" -> return hundreds[3] + " and " + tens[1] + units[2]
                "424" -> return hundreds[3] + " and " + tens[1] + units[3]
                "425" -> return hundreds[3] + " and " + tens[1] + units[4]
                "426" -> return hundreds[3] + " and " + tens[1] + units[5]
                "427" -> return hundreds[3] + " and " + tens[1] + units[6]
                "428" -> return hundreds[3] + " and " + tens[1] + units[7]
                "429" -> return hundreds[3] + " and " + tens[1] + units[8]
                "430" -> return hundreds[3] + " and " + tens[2]
                "431" -> return hundreds[3] + " and " + tens[2] + units[0]
                "432" -> return hundreds[3] + " and " + tens[2] + units[1]
                "433" -> return hundreds[3] + " and " + tens[2] + units[2]
                "434" -> return hundreds[3] + " and " + tens[2] + units[3]
                "435" -> return hundreds[3] + " and " + tens[2] + units[4]
                "436" -> return hundreds[3] + " and " + tens[2] + units[5]
                "437" -> return hundreds[3] + " and " + tens[2] + units[6]
                "438" -> return hundreds[3] + " and " + tens[2] + units[7]
                "439" -> return hundreds[3] + " and " + tens[2] + units[8]
                "440" -> return hundreds[3] + " and " + tens[3]
                "441" -> return hundreds[3] + " and " + tens[3] + units[0]
                "442" -> return hundreds[3] + " and " + tens[3] + units[1]
                "443" -> return hundreds[3] + " and " + tens[3] + units[2]
                "444" -> return hundreds[3] + " and " + tens[3] + units[3]
                "445" -> return hundreds[3] + " and " + tens[3] + units[4]
                "446" -> return hundreds[3] + " and " + tens[3] + units[5]
                "447" -> return hundreds[3] + " and " + tens[3] + units[6]
                "448" -> return hundreds[3] + " and " + tens[3] + units[7]
                "449" -> return hundreds[3] + " and " + tens[3] + units[8]
                "450" -> return hundreds[3] + " and " + tens[4]
                "451" -> return hundreds[3] + " and " + tens[4] + units[0]
                "452" -> return hundreds[3] + " and " + tens[4] + units[1]
                "453" -> return hundreds[3] + " and " + tens[4] + units[2]
                "454" -> return hundreds[3] + " and " + tens[4] + units[3]
                "455" -> return hundreds[3] + " and " + tens[4] + units[4]
                "456" -> return hundreds[3] + " and " + tens[4] + units[5]
                "457" -> return hundreds[3] + " and " + tens[4] + units[6]
                "458" -> return hundreds[3] + " and " + tens[4] + units[7]
                "459" -> return hundreds[3] + " and " + tens[4] + units[8]
                "460" -> return hundreds[3] + " and " + tens[5]
                "461" -> return hundreds[3] + " and " + tens[5] + units[0]
                "462" -> return hundreds[3] + " and " + tens[5] + units[1]
                "463" -> return hundreds[3] + " and " + tens[5] + units[2]
                "464" -> return hundreds[3] + " and " + tens[5] + units[3]
                "465" -> return hundreds[3] + " and " + tens[5] + units[4]
                "466" -> return hundreds[3] + " and " + tens[5] + units[5]
                "467" -> return hundreds[3] + " and " + tens[5] + units[6]
                "468" -> return hundreds[3] + " and " + tens[5] + units[7]
                "469" -> return hundreds[3] + " and " + tens[5] + units[8]
                "470" -> return hundreds[3] + " and " + tens[6]
                "471" -> return hundreds[3] + " and " + tens[6] + units[0]
                "472" -> return hundreds[3] + " and " + tens[6] + units[1]
                "473" -> return hundreds[3] + " and " + tens[6] + units[2]
                "474" -> return hundreds[3] + " and " + tens[6] + units[3]
                "475" -> return hundreds[3] + " and " + tens[6] + units[4]
                "476" -> return hundreds[3] + " and " + tens[6] + units[5]
                "477" -> return hundreds[3] + " and " + tens[6] + units[6]
                "478" -> return hundreds[3] + " and " + tens[6] + units[7]
                "479" -> return hundreds[3] + " and " + tens[6] + units[8]
                "480" -> return hundreds[3] + " and " + tens[7]
                "481" -> return hundreds[3] + " and " + tens[7] + units[0]
                "482" -> return hundreds[3] + " and " + tens[7] + units[1]
                "483" -> return hundreds[3] + " and " + tens[7] + units[2]
                "484" -> return hundreds[3] + " and " + tens[7] + units[3]
                "485" -> return hundreds[3] + " and " + tens[7] + units[4]
                "486" -> return hundreds[3] + " and " + tens[7] + units[5]
                "487" -> return hundreds[3] + " and " + tens[7] + units[6]
                "488" -> return hundreds[3] + " and " + tens[7] + units[7]
                "489" -> return hundreds[3] + " and " + tens[7] + units[8]
                "490" -> return hundreds[3] + " and " + tens[8]
                "491" -> return hundreds[3] + " and " + tens[8] + units[0]
                "492" -> return hundreds[3] + " and " + tens[8] + units[1]
                "493" -> return hundreds[3] + " and " + tens[8] + units[2]
                "494" -> return hundreds[3] + " and " + tens[8] + units[3]
                "495" -> return hundreds[3] + " and " + tens[8] + units[4]
                "496" -> return hundreds[3] + " and " + tens[8] + units[5]
                "497" -> return hundreds[3] + " and " + tens[8] + units[6]
                "498" -> return hundreds[3] + " and " + tens[8] + units[7]
                "499" -> return hundreds[3] + " and " + tens[8] + units[8]
            }

        } else if ((num.length == 3) && (num[1] == '5')) {
            when (num) {
                "500" -> return hundreds[4]
                "501" -> return hundreds[4] + " and " + units[0]
                "502" -> return hundreds[4] + " and " + units[1]
                "503" -> return hundreds[4] + " and " + units[2]
                "504" -> return hundreds[4] + " and " + units[3]
                "505" -> return hundreds[4] + " and " + units[4]
                "506" -> return hundreds[4] + " and " + units[5]
                "507" -> return hundreds[4] + " and " + units[6]
                "508" -> return hundreds[4] + " and " + units[7]
                "509" -> return hundreds[4] + " and " + units[8]
                "510" -> return hundreds[4] + " and " + tens[0]
                "511" -> return hundreds[4] + " and " + teens[0]
                "512" -> return hundreds[4] + " and " + teens[1]
                "513" -> return hundreds[4] + " and " + teens[2]
                "514" -> return hundreds[4] + " and " + teens[3]
                "515" -> return hundreds[4] + " and " + teens[4]
                "516" -> return hundreds[4] + " and " + teens[5]
                "517" -> return hundreds[4] + " and " + teens[6]
                "518" -> return hundreds[4] + " and " + teens[7]
                "519" -> return hundreds[4] + " and " + teens[8]
                "520" -> return hundreds[4] + " and " + tens[1]
                "521" -> return hundreds[4] + " and " + tens[1] + units[0]
                "522" -> return hundreds[4] + " and " + tens[1] + units[1]
                "523" -> return hundreds[4] + " and " + tens[1] + units[2]
                "524" -> return hundreds[4] + " and " + tens[1] + units[3]
                "525" -> return hundreds[4] + " and " + tens[1] + units[4]
                "526" -> return hundreds[4] + " and " + tens[1] + units[5]
                "527" -> return hundreds[4] + " and " + tens[1] + units[6]
                "528" -> return hundreds[4] + " and " + tens[1] + units[7]
                "529" -> return hundreds[4] + " and " + tens[1] + units[8]
                "530" -> return hundreds[4] + " and " + tens[2]
                "531" -> return hundreds[4] + " and " + tens[2] + units[0]
                "532" -> return hundreds[4] + " and " + tens[2] + units[1]
                "533" -> return hundreds[4] + " and " + tens[2] + units[2]
                "534" -> return hundreds[4] + " and " + tens[2] + units[3]
                "535" -> return hundreds[4] + " and " + tens[2] + units[4]
                "536" -> return hundreds[4] + " and " + tens[2] + units[5]
                "537" -> return hundreds[4] + " and " + tens[2] + units[6]
                "538" -> return hundreds[4] + " and " + tens[2] + units[7]
                "539" -> return hundreds[4] + " and " + tens[2] + units[8]
                "540" -> return hundreds[4] + " and " + tens[3]
                "541" -> return hundreds[4] + " and " + tens[3] + units[0]
                "542" -> return hundreds[4] + " and " + tens[3] + units[1]
                "543" -> return hundreds[4] + " and " + tens[3] + units[2]
                "544" -> return hundreds[4] + " and " + tens[3] + units[3]
                "545" -> return hundreds[4] + " and " + tens[3] + units[4]
                "546" -> return hundreds[4] + " and " + tens[3] + units[5]
                "547" -> return hundreds[4] + " and " + tens[3] + units[6]
                "548" -> return hundreds[4] + " and " + tens[3] + units[7]
                "549" -> return hundreds[4] + " and " + tens[3] + units[8]
                "550" -> return hundreds[4] + " and " + tens[4]
                "551" -> return hundreds[4] + " and " + tens[4] + units[0]
                "552" -> return hundreds[4] + " and " + tens[4] + units[1]
                "553" -> return hundreds[4] + " and " + tens[4] + units[2]
                "554" -> return hundreds[4] + " and " + tens[4] + units[3]
                "555" -> return hundreds[4] + " and " + tens[4] + units[4]
                "556" -> return hundreds[4] + " and " + tens[4] + units[5]
                "557" -> return hundreds[4] + " and " + tens[4] + units[6]
                "558" -> return hundreds[4] + " and " + tens[4] + units[7]
                "559" -> return hundreds[4] + " and " + tens[4] + units[8]
                "560" -> return hundreds[4] + " and " + tens[5]
                "561" -> return hundreds[4] + " and " + tens[5] + units[0]
                "562" -> return hundreds[4] + " and " + tens[5] + units[1]
                "563" -> return hundreds[4] + " and " + tens[5] + units[2]
                "564" -> return hundreds[4] + " and " + tens[5] + units[3]
                "565" -> return hundreds[4] + " and " + tens[5] + units[4]
                "566" -> return hundreds[4] + " and " + tens[5] + units[5]
                "567" -> return hundreds[4] + " and " + tens[5] + units[6]
                "568" -> return hundreds[4] + " and " + tens[5] + units[7]
                "569" -> return hundreds[4] + " and " + tens[5] + units[8]
                "570" -> return hundreds[4] + " and " + tens[6]
                "571" -> return hundreds[4] + " and " + tens[6] + units[0]
                "572" -> return hundreds[4] + " and " + tens[6] + units[1]
                "573" -> return hundreds[4] + " and " + tens[6] + units[2]
                "574" -> return hundreds[4] + " and " + tens[6] + units[3]
                "575" -> return hundreds[4] + " and " + tens[6] + units[4]
                "576" -> return hundreds[4] + " and " + tens[6] + units[5]
                "577" -> return hundreds[4] + " and " + tens[6] + units[6]
                "578" -> return hundreds[4] + " and " + tens[6] + units[7]
                "579" -> return hundreds[4] + " and " + tens[6] + units[8]
                "580" -> return hundreds[4] + " and " + tens[7]
                "581" -> return hundreds[4] + " and " + tens[7] + units[0]
                "582" -> return hundreds[4] + " and " + tens[7] + units[1]
                "583" -> return hundreds[4] + " and " + tens[7] + units[2]
                "584" -> return hundreds[4] + " and " + tens[7] + units[3]
                "585" -> return hundreds[4] + " and " + tens[7] + units[4]
                "586" -> return hundreds[4] + " and " + tens[7] + units[5]
                "587" -> return hundreds[4] + " and " + tens[7] + units[6]
                "588" -> return hundreds[4] + " and " + tens[7] + units[7]
                "589" -> return hundreds[4] + " and " + tens[7] + units[8]
                "590" -> return hundreds[4] + " and " + tens[8]
                "591" -> return hundreds[4] + " and " + tens[8] + units[0]
                "592" -> return hundreds[4] + " and " + tens[8] + units[1]
                "593" -> return hundreds[4] + " and " + tens[8] + units[2]
                "594" -> return hundreds[4] + " and " + tens[8] + units[3]
                "595" -> return hundreds[4] + " and " + tens[8] + units[4]
                "596" -> return hundreds[4] + " and " + tens[8] + units[5]
                "597" -> return hundreds[4] + " and " + tens[8] + units[6]
                "598" -> return hundreds[4] + " and " + tens[8] + units[7]
                "599" -> return hundreds[4] + " and " + tens[8] + units[8]
            }
        } else if ((num.length == 3) && (num[1] == '6')) {
            when (num) {
                "600" -> return hundreds[5]
                "601" -> return hundreds[5] + " and " + units[0]
                "602" -> return hundreds[5] + " and " + units[1]
                "603" -> return hundreds[5] + " and " + units[2]
                "604" -> return hundreds[5] + " and " + units[3]
                "605" -> return hundreds[5] + " and " + units[4]
                "606" -> return hundreds[5] + " and " + units[5]
                "607" -> return hundreds[5] + " and " + units[6]
                "608" -> return hundreds[5] + " and " + units[7]
                "609" -> return hundreds[5] + " and " + units[8]
                "610" -> return hundreds[5] + " and " + tens[0]
                "611" -> return hundreds[5] + " and " + teens[0]
                "612" -> return hundreds[5] + " and " + teens[1]
                "613" -> return hundreds[5] + " and " + teens[2]
                "614" -> return hundreds[5] + " and " + teens[3]
                "615" -> return hundreds[5] + " and " + teens[4]
                "616" -> return hundreds[5] + " and " + teens[5]
                "617" -> return hundreds[5] + " and " + teens[6]
                "618" -> return hundreds[5] + " and " + teens[7]
                "619" -> return hundreds[5] + " and " + teens[8]
                "620" -> return hundreds[5] + " and " + tens[1]
                "621" -> return hundreds[5] + " and " + tens[1] + units[0]
                "622" -> return hundreds[5] + " and " + tens[1] + units[1]
                "623" -> return hundreds[5] + " and " + tens[1] + units[2]
                "624" -> return hundreds[5] + " and " + tens[1] + units[3]
                "625" -> return hundreds[5] + " and " + tens[1] + units[4]
                "626" -> return hundreds[5] + " and " + tens[1] + units[5]
                "627" -> return hundreds[5] + " and " + tens[1] + units[6]
                "628" -> return hundreds[5] + " and " + tens[1] + units[7]
                "629" -> return hundreds[5] + " and " + tens[1] + units[8]
                "630" -> return hundreds[5] + " and " + tens[2]
                "631" -> return hundreds[5] + " and " + tens[2] + units[0]
                "632" -> return hundreds[5] + " and " + tens[2] + units[1]
                "633" -> return hundreds[5] + " and " + tens[2] + units[2]
                "634" -> return hundreds[5] + " and " + tens[2] + units[3]
                "635" -> return hundreds[5] + " and " + tens[2] + units[4]
                "636" -> return hundreds[5] + " and " + tens[2] + units[5]
                "637" -> return hundreds[5] + " and " + tens[2] + units[6]
                "638" -> return hundreds[5] + " and " + tens[2] + units[7]
                "639" -> return hundreds[5] + " and " + tens[2] + units[8]
                "640" -> return hundreds[5] + " and " + tens[3]
                "641" -> return hundreds[5] + " and " + tens[3] + units[0]
                "642" -> return hundreds[5] + " and " + tens[3] + units[1]
                "643" -> return hundreds[5] + " and " + tens[3] + units[2]
                "644" -> return hundreds[5] + " and " + tens[3] + units[3]
                "645" -> return hundreds[5] + " and " + tens[3] + units[4]
                "646" -> return hundreds[5] + " and " + tens[3] + units[5]
                "647" -> return hundreds[5] + " and " + tens[3] + units[6]
                "648" -> return hundreds[5] + " and " + tens[3] + units[7]
                "649" -> return hundreds[5] + " and " + tens[3] + units[8]
                "650" -> return hundreds[5] + " and " + tens[4]
                "651" -> return hundreds[5] + " and " + tens[4] + units[0]
                "652" -> return hundreds[5] + " and " + tens[4] + units[1]
                "653" -> return hundreds[5] + " and " + tens[4] + units[2]
                "654" -> return hundreds[5] + " and " + tens[4] + units[3]
                "655" -> return hundreds[5] + " and " + tens[4] + units[4]
                "656" -> return hundreds[5] + " and " + tens[4] + units[5]
                "657" -> return hundreds[5] + " and " + tens[4] + units[6]
                "658" -> return hundreds[5] + " and " + tens[4] + units[7]
                "659" -> return hundreds[5] + " and " + tens[4] + units[8]
                "660" -> return hundreds[5] + " and " + tens[5]
                "661" -> return hundreds[5] + " and " + tens[5] + units[0]
                "662" -> return hundreds[5] + " and " + tens[5] + units[1]
                "663" -> return hundreds[5] + " and " + tens[5] + units[2]
                "664" -> return hundreds[5] + " and " + tens[5] + units[3]
                "665" -> return hundreds[5] + " and " + tens[5] + units[4]
                "666" -> return hundreds[5] + " and " + tens[5] + units[5]
                "667" -> return hundreds[5] + " and " + tens[5] + units[6]
                "668" -> return hundreds[5] + " and " + tens[5] + units[7]
                "669" -> return hundreds[5] + " and " + tens[5] + units[8]
                "670" -> return hundreds[5] + " and " + tens[6]
                "671" -> return hundreds[5] + " and " + tens[6] + units[0]
                "672" -> return hundreds[5] + " and " + tens[6] + units[1]
                "673" -> return hundreds[5] + " and " + tens[6] + units[2]
                "674" -> return hundreds[5] + " and " + tens[6] + units[3]
                "675" -> return hundreds[5] + " and " + tens[6] + units[4]
                "676" -> return hundreds[5] + " and " + tens[6] + units[5]
                "677" -> return hundreds[5] + " and " + tens[6] + units[6]
                "678" -> return hundreds[5] + " and " + tens[6] + units[7]
                "679" -> return hundreds[5] + " and " + tens[6] + units[8]
                "680" -> return hundreds[5] + " and " + tens[7]
                "681" -> return hundreds[5] + " and " + tens[7] + units[0]
                "682" -> return hundreds[5] + " and " + tens[7] + units[1]
                "683" -> return hundreds[5] + " and " + tens[7] + units[2]
                "684" -> return hundreds[5] + " and " + tens[7] + units[3]
                "685" -> return hundreds[5] + " and " + tens[7] + units[4]
                "686" -> return hundreds[5] + " and " + tens[7] + units[5]
                "687" -> return hundreds[5] + " and " + tens[7] + units[6]
                "688" -> return hundreds[5] + " and " + tens[7] + units[7]
                "689" -> return hundreds[5] + " and " + tens[7] + units[8]
                "690" -> return hundreds[5] + " and " + tens[8]
                "691" -> return hundreds[5] + " and " + tens[8] + units[0]
                "692" -> return hundreds[5] + " and " + tens[8] + units[1]
                "693" -> return hundreds[5] + " and " + tens[8] + units[2]
                "694" -> return hundreds[5] + " and " + tens[8] + units[3]
                "695" -> return hundreds[5] + " and " + tens[8] + units[4]
                "696" -> return hundreds[5] + " and " + tens[8] + units[5]
                "697" -> return hundreds[5] + " and " + tens[8] + units[6]
                "698" -> return hundreds[5] + " and " + tens[8] + units[7]
                "699" -> return hundreds[5] + " and " + tens[8] + units[8]
            }
        } else if ((num.length == 3) && (num[1] == '7')) {
            when (num) {
                "700" -> return hundreds[6]
                "701" -> return hundreds[6] + " and " + units[0]
                "702" -> return hundreds[6] + " and " + units[1]
                "703" -> return hundreds[6] + " and " + units[2]
                "704" -> return hundreds[6] + " and " + units[3]
                "705" -> return hundreds[6] + " and " + units[4]
                "706" -> return hundreds[6] + " and " + units[5]
                "707" -> return hundreds[6] + " and " + units[6]
                "708" -> return hundreds[6] + " and " + units[7]
                "709" -> return hundreds[6] + " and " + units[8]
                "710" -> return hundreds[6] + " and " + tens[0]
                "711" -> return hundreds[6] + " and " + teens[0]
                "712" -> return hundreds[6] + " and " + teens[1]
                "713" -> return hundreds[6] + " and " + teens[2]
                "714" -> return hundreds[6] + " and " + teens[3]
                "715" -> return hundreds[6] + " and " + teens[4]
                "716" -> return hundreds[6] + " and " + teens[5]
                "717" -> return hundreds[6] + " and " + teens[6]
                "718" -> return hundreds[6] + " and " + teens[7]
                "719" -> return hundreds[6] + " and " + teens[8]
                "720" -> return hundreds[6] + " and " + tens[1]
                "721" -> return hundreds[6] + " and " + tens[1] + units[0]
                "722" -> return hundreds[6] + " and " + tens[1] + units[1]
                "723" -> return hundreds[6] + " and " + tens[1] + units[2]
                "724" -> return hundreds[6] + " and " + tens[1] + units[3]
                "725" -> return hundreds[6] + " and " + tens[1] + units[4]
                "726" -> return hundreds[6] + " and " + tens[1] + units[5]
                "727" -> return hundreds[6] + " and " + tens[1] + units[6]
                "728" -> return hundreds[6] + " and " + tens[1] + units[7]
                "729" -> return hundreds[6] + " and " + tens[1] + units[8]
                "730" -> return hundreds[6] + " and " + tens[2]
                "731" -> return hundreds[6] + " and " + tens[2] + units[0]
                "732" -> return hundreds[6] + " and " + tens[2] + units[1]
                "733" -> return hundreds[6] + " and " + tens[2] + units[2]
                "734" -> return hundreds[6] + " and " + tens[2] + units[3]
                "735" -> return hundreds[6] + " and " + tens[2] + units[4]
                "736" -> return hundreds[6] + " and " + tens[2] + units[5]
                "737" -> return hundreds[6] + " and " + tens[2] + units[6]
                "738" -> return hundreds[6] + " and " + tens[2] + units[7]
                "739" -> return hundreds[6] + " and " + tens[2] + units[8]
                "740" -> return hundreds[6] + " and " + tens[3]
                "741" -> return hundreds[6] + " and " + tens[3] + units[0]
                "742" -> return hundreds[6] + " and " + tens[3] + units[1]
                "743" -> return hundreds[6] + " and " + tens[3] + units[2]
                "744" -> return hundreds[6] + " and " + tens[3] + units[3]
                "745" -> return hundreds[6] + " and " + tens[3] + units[4]
                "746" -> return hundreds[6] + " and " + tens[3] + units[5]
                "747" -> return hundreds[6] + " and " + tens[3] + units[6]
                "748" -> return hundreds[6] + " and " + tens[3] + units[7]
                "749" -> return hundreds[6] + " and " + tens[3] + units[8]
                "750" -> return hundreds[6] + " and " + tens[4]
                "751" -> return hundreds[6] + " and " + tens[4] + units[0]
                "752" -> return hundreds[6] + " and " + tens[4] + units[1]
                "753" -> return hundreds[6] + " and " + tens[4] + units[2]
                "754" -> return hundreds[6] + " and " + tens[4] + units[3]
                "755" -> return hundreds[6] + " and " + tens[4] + units[4]
                "756" -> return hundreds[6] + " and " + tens[4] + units[5]
                "757" -> return hundreds[6] + " and " + tens[4] + units[6]
                "758" -> return hundreds[6] + " and " + tens[4] + units[7]
                "759" -> return hundreds[6] + " and " + tens[4] + units[8]
                "760" -> return hundreds[6] + " and " + tens[5]
                "761" -> return hundreds[6] + " and " + tens[5] + units[0]
                "762" -> return hundreds[6] + " and " + tens[5] + units[1]
                "763" -> return hundreds[6] + " and " + tens[5] + units[2]
                "764" -> return hundreds[6] + " and " + tens[5] + units[3]
                "765" -> return hundreds[6] + " and " + tens[5] + units[4]
                "766" -> return hundreds[6] + " and " + tens[5] + units[5]
                "767" -> return hundreds[6] + " and " + tens[5] + units[6]
                "768" -> return hundreds[6] + " and " + tens[5] + units[7]
                "769" -> return hundreds[6] + " and " + tens[5] + units[8]
                "770" -> return hundreds[6] + " and " + tens[6]
                "771" -> return hundreds[6] + " and " + tens[6] + units[0]
                "772" -> return hundreds[6] + " and " + tens[6] + units[1]
                "773" -> return hundreds[6] + " and " + tens[6] + units[2]
                "774" -> return hundreds[6] + " and " + tens[6] + units[3]
                "775" -> return hundreds[6] + " and " + tens[6] + units[4]
                "776" -> return hundreds[6] + " and " + tens[6] + units[5]
                "777" -> return hundreds[6] + " and " + tens[6] + units[6]
                "778" -> return hundreds[6] + " and " + tens[6] + units[7]
                "779" -> return hundreds[6] + " and " + tens[6] + units[8]
                "780" -> return hundreds[6] + " and " + tens[7]
                "781" -> return hundreds[6] + " and " + tens[7] + units[0]
                "782" -> return hundreds[6] + " and " + tens[7] + units[1]
                "783" -> return hundreds[6] + " and " + tens[7] + units[2]
                "784" -> return hundreds[6] + " and " + tens[7] + units[3]
                "785" -> return hundreds[6] + " and " + tens[7] + units[4]
                "786" -> return hundreds[6] + " and " + tens[7] + units[5]
                "787" -> return hundreds[6] + " and " + tens[7] + units[6]
                "788" -> return hundreds[6] + " and " + tens[7] + units[7]
                "789" -> return hundreds[6] + " and " + tens[7] + units[8]
                "790" -> return hundreds[6] + " and " + tens[8]
                "791" -> return hundreds[6] + " and " + tens[8] + units[0]
                "792" -> return hundreds[6] + " and " + tens[8] + units[1]
                "793" -> return hundreds[6] + " and " + tens[8] + units[2]
                "794" -> return hundreds[6] + " and " + tens[8] + units[3]
                "795" -> return hundreds[6] + " and " + tens[8] + units[4]
                "796" -> return hundreds[6] + " and " + tens[8] + units[5]
                "797" -> return hundreds[6] + " and " + tens[8] + units[6]
                "798" -> return hundreds[6] + " and " + tens[8] + units[7]
                "799" -> return hundreds[6] + " and " + tens[8] + units[8]
            }
        } else if ((num.length == 3) && (num[1] == '8')) {
            when (num) {
                "800" -> return hundreds[7]
                "801" -> return hundreds[7] + " and " + units[0]
                "802" -> return hundreds[7] + " and " + units[1]
                "803" -> return hundreds[7] + " and " + units[2]
                "804" -> return hundreds[7] + " and " + units[3]
                "805" -> return hundreds[7] + " and " + units[4]
                "806" -> return hundreds[7] + " and " + units[5]
                "807" -> return hundreds[7] + " and " + units[6]
                "808" -> return hundreds[7] + " and " + units[7]
                "809" -> return hundreds[7] + " and " + units[8]
                "810" -> return hundreds[7] + " and " + tens[0]
                "811" -> return hundreds[7] + " and " + teens[0]
                "812" -> return hundreds[7] + " and " + teens[1]
                "813" -> return hundreds[7] + " and " + teens[2]
                "814" -> return hundreds[7] + " and " + teens[3]
                "815" -> return hundreds[7] + " and " + teens[4]
                "816" -> return hundreds[7] + " and " + teens[5]
                "817" -> return hundreds[7] + " and " + teens[6]
                "818" -> return hundreds[7] + " and " + teens[7]
                "819" -> return hundreds[7] + " and " + teens[8]
                "820" -> return hundreds[7] + " and " + tens[1]
                "821" -> return hundreds[7] + " and " + tens[1] + units[0]
                "822" -> return hundreds[7] + " and " + tens[1] + units[1]
                "823" -> return hundreds[7] + " and " + tens[1] + units[2]
                "824" -> return hundreds[7] + " and " + tens[1] + units[3]
                "825" -> return hundreds[7] + " and " + tens[1] + units[4]
                "826" -> return hundreds[7] + " and " + tens[1] + units[5]
                "827" -> return hundreds[7] + " and " + tens[1] + units[6]
                "828" -> return hundreds[7] + " and " + tens[1] + units[7]
                "829" -> return hundreds[7] + " and " + tens[1] + units[8]
                "830" -> return hundreds[7] + " and " + tens[2]
                "831" -> return hundreds[7] + " and " + tens[2] + units[0]
                "832" -> return hundreds[7] + " and " + tens[2] + units[1]
                "833" -> return hundreds[7] + " and " + tens[2] + units[2]
                "834" -> return hundreds[7] + " and " + tens[2] + units[3]
                "835" -> return hundreds[7] + " and " + tens[2] + units[4]
                "836" -> return hundreds[7] + " and " + tens[2] + units[5]
                "837" -> return hundreds[7] + " and " + tens[2] + units[6]
                "838" -> return hundreds[7] + " and " + tens[2] + units[7]
                "839" -> return hundreds[7] + " and " + tens[2] + units[8]
                "840" -> return hundreds[7] + " and " + tens[3]
                "841" -> return hundreds[7] + " and " + tens[3] + units[0]
                "842" -> return hundreds[7] + " and " + tens[3] + units[1]
                "843" -> return hundreds[7] + " and " + tens[3] + units[2]
                "844" -> return hundreds[7] + " and " + tens[3] + units[3]
                "845" -> return hundreds[7] + " and " + tens[3] + units[4]
                "846" -> return hundreds[7] + " and " + tens[3] + units[5]
                "847" -> return hundreds[7] + " and " + tens[3] + units[6]
                "848" -> return hundreds[7] + " and " + tens[3] + units[7]
                "849" -> return hundreds[7] + " and " + tens[3] + units[8]
                "850" -> return hundreds[7] + " and " + tens[4]
                "851" -> return hundreds[7] + " and " + tens[4] + units[0]
                "852" -> return hundreds[7] + " and " + tens[4] + units[1]
                "853" -> return hundreds[7] + " and " + tens[4] + units[2]
                "854" -> return hundreds[7] + " and " + tens[4] + units[3]
                "855" -> return hundreds[7] + " and " + tens[4] + units[4]
                "856" -> return hundreds[7] + " and " + tens[4] + units[5]
                "857" -> return hundreds[7] + " and " + tens[4] + units[6]
                "858" -> return hundreds[7] + " and " + tens[4] + units[7]
                "859" -> return hundreds[7] + " and " + tens[4] + units[8]
                "860" -> return hundreds[7] + " and " + tens[5]
                "861" -> return hundreds[7] + " and " + tens[5] + units[0]
                "862" -> return hundreds[7] + " and " + tens[5] + units[1]
                "863" -> return hundreds[7] + " and " + tens[5] + units[2]
                "864" -> return hundreds[7] + " and " + tens[5] + units[3]
                "865" -> return hundreds[7] + " and " + tens[5] + units[4]
                "866" -> return hundreds[7] + " and " + tens[5] + units[5]
                "867" -> return hundreds[7] + " and " + tens[5] + units[6]
                "868" -> return hundreds[7] + " and " + tens[5] + units[7]
                "869" -> return hundreds[7] + " and " + tens[5] + units[8]
                "870" -> return hundreds[7] + " and " + tens[6]
                "871" -> return hundreds[7] + " and " + tens[6] + units[0]
                "872" -> return hundreds[7] + " and " + tens[6] + units[1]
                "873" -> return hundreds[7] + " and " + tens[6] + units[2]
                "874" -> return hundreds[7] + " and " + tens[6] + units[3]
                "875" -> return hundreds[7] + " and " + tens[6] + units[4]
                "876" -> return hundreds[7] + " and " + tens[6] + units[5]
                "877" -> return hundreds[7] + " and " + tens[6] + units[6]
                "878" -> return hundreds[7] + " and " + tens[6] + units[7]
                "879" -> return hundreds[7] + " and " + tens[6] + units[8]
                "880" -> return hundreds[7] + " and " + tens[7]
                "881" -> return hundreds[7] + " and " + tens[7] + units[0]
                "882" -> return hundreds[7] + " and " + tens[7] + units[1]
                "883" -> return hundreds[7] + " and " + tens[7] + units[2]
                "884" -> return hundreds[7] + " and " + tens[7] + units[3]
                "885" -> return hundreds[7] + " and " + tens[7] + units[4]
                "886" -> return hundreds[7] + " and " + tens[7] + units[5]
                "887" -> return hundreds[7] + " and " + tens[7] + units[6]
                "888" -> return hundreds[7] + " and " + tens[7] + units[7]
                "889" -> return hundreds[7] + " and " + tens[7] + units[8]
                "890" -> return hundreds[7] + " and " + tens[8]
                "891" -> return hundreds[7] + " and " + tens[8] + units[0]
                "892" -> return hundreds[7] + " and " + tens[8] + units[1]
                "893" -> return hundreds[7] + " and " + tens[8] + units[2]
                "894" -> return hundreds[7] + " and " + tens[8] + units[3]
                "895" -> return hundreds[7] + " and " + tens[8] + units[4]
                "896" -> return hundreds[7] + " and " + tens[8] + units[5]
                "897" -> return hundreds[7] + " and " + tens[8] + units[6]
                "898" -> return hundreds[7] + " and " + tens[8] + units[7]
                "899" -> return hundreds[7] + " and " + tens[8] + units[8]
            }
        } else if ((num.length == 3) && (num[1] == '9')) {
            when (num) {
                "900" -> return hundreds[8]
                "901" -> return hundreds[8] + " and " + units[0]
                "902" -> return hundreds[8] + " and " + units[1]
                "903" -> return hundreds[8] + " and " + units[2]
                "904" -> return hundreds[8] + " and " + units[3]
                "905" -> return hundreds[8] + " and " + units[4]
                "906" -> return hundreds[8] + " and " + units[5]
                "907" -> return hundreds[8] + " and " + units[6]
                "908" -> return hundreds[8] + " and " + units[7]
                "909" -> return hundreds[8] + " and " + units[8]
                "910" -> return hundreds[8] + " and " + tens[0]
                "911" -> return hundreds[8] + " and " + teens[0]
                "912" -> return hundreds[8] + " and " + teens[1]
                "913" -> return hundreds[8] + " and " + teens[2]
                "914" -> return hundreds[8] + " and " + teens[3]
                "915" -> return hundreds[8] + " and " + teens[4]
                "916" -> return hundreds[8] + " and " + teens[5]
                "917" -> return hundreds[8] + " and " + teens[6]
                "918" -> return hundreds[8] + " and " + teens[7]
                "919" -> return hundreds[8] + " and " + teens[8]
                "920" -> return hundreds[8] + " and " + tens[1]
                "921" -> return hundreds[8] + " and " + tens[1] + units[0]
                "922" -> return hundreds[8] + " and " + tens[1] + units[1]
                "923" -> return hundreds[8] + " and " + tens[1] + units[2]
                "924" -> return hundreds[8] + " and " + tens[1] + units[3]
                "925" -> return hundreds[8] + " and " + tens[1] + units[4]
                "926" -> return hundreds[8] + " and " + tens[1] + units[5]
                "927" -> return hundreds[8] + " and " + tens[1] + units[6]
                "928" -> return hundreds[8] + " and " + tens[1] + units[7]
                "929" -> return hundreds[8] + " and " + tens[1] + units[8]
                "930" -> return hundreds[8] + " and " + tens[2]
                "931" -> return hundreds[8] + " and " + tens[2] + units[0]
                "932" -> return hundreds[8] + " and " + tens[2] + units[1]
                "933" -> return hundreds[8] + " and " + tens[2] + units[2]
                "934" -> return hundreds[8] + " and " + tens[2] + units[3]
                "935" -> return hundreds[8] + " and " + tens[2] + units[4]
                "936" -> return hundreds[8] + " and " + tens[2] + units[5]
                "937" -> return hundreds[8] + " and " + tens[2] + units[6]
                "938" -> return hundreds[8] + " and " + tens[2] + units[7]
                "939" -> return hundreds[8] + " and " + tens[2] + units[8]
                "940" -> return hundreds[8] + " and " + tens[3]
                "941" -> return hundreds[8] + " and " + tens[3] + units[0]
                "942" -> return hundreds[8] + " and " + tens[3] + units[1]
                "943" -> return hundreds[8] + " and " + tens[3] + units[2]
                "944" -> return hundreds[8] + " and " + tens[3] + units[3]
                "945" -> return hundreds[8] + " and " + tens[3] + units[4]
                "946" -> return hundreds[8] + " and " + tens[3] + units[5]
                "947" -> return hundreds[8] + " and " + tens[3] + units[6]
                "948" -> return hundreds[8] + " and " + tens[3] + units[7]
                "949" -> return hundreds[8] + " and " + tens[3] + units[8]
                "950" -> return hundreds[8] + " and " + tens[4]
                "951" -> return hundreds[8] + " and " + tens[4] + units[0]
                "952" -> return hundreds[8] + " and " + tens[4] + units[1]
                "953" -> return hundreds[8] + " and " + tens[4] + units[2]
                "954" -> return hundreds[8] + " and " + tens[4] + units[3]
                "955" -> return hundreds[8] + " and " + tens[4] + units[4]
                "956" -> return hundreds[8] + " and " + tens[4] + units[5]
                "957" -> return hundreds[8] + " and " + tens[4] + units[6]
                "958" -> return hundreds[8] + " and " + tens[4] + units[7]
                "959" -> return hundreds[8] + " and " + tens[4] + units[8]
                "960" -> return hundreds[8] + " and " + tens[5]
                "961" -> return hundreds[8] + " and " + tens[5] + units[0]
                "962" -> return hundreds[8] + " and " + tens[5] + units[1]
                "963" -> return hundreds[8] + " and " + tens[5] + units[2]
                "964" -> return hundreds[8] + " and " + tens[5] + units[3]
                "965" -> return hundreds[8] + " and " + tens[5] + units[4]
                "966" -> return hundreds[8] + " and " + tens[5] + units[5]
                "967" -> return hundreds[8] + " and " + tens[5] + units[6]
                "968" -> return hundreds[8] + " and " + tens[5] + units[7]
                "969" -> return hundreds[8] + " and " + tens[5] + units[8]
                "970" -> return hundreds[8] + " and " + tens[6]
                "971" -> return hundreds[8] + " and " + tens[6] + units[0]
                "972" -> return hundreds[8] + " and " + tens[6] + units[1]
                "973" -> return hundreds[8] + " and " + tens[6] + units[2]
                "974" -> return hundreds[8] + " and " + tens[6] + units[3]
                "975" -> return hundreds[8] + " and " + tens[6] + units[4]
                "976" -> return hundreds[8] + " and " + tens[6] + units[5]
                "977" -> return hundreds[8] + " and " + tens[6] + units[6]
                "978" -> return hundreds[8] + " and " + tens[6] + units[7]
                "979" -> return hundreds[8] + " and " + tens[6] + units[8]
                "980" -> return hundreds[8] + " and " + tens[7]
                "981" -> return hundreds[8] + " and " + tens[7] + units[0]
                "982" -> return hundreds[8] + " and " + tens[7] + units[1]
                "983" -> return hundreds[8] + " and " + tens[7] + units[2]
                "984" -> return hundreds[8] + " and " + tens[7] + units[3]
                "985" -> return hundreds[8] + " and " + tens[7] + units[4]
                "986" -> return hundreds[8] + " and " + tens[7] + units[5]
                "987" -> return hundreds[8] + " and " + tens[7] + units[6]
                "988" -> return hundreds[8] + " and " + tens[7] + units[7]
                "989" -> return hundreds[8] + " and " + tens[7] + units[8]
                "990" -> return hundreds[8] + " and " + tens[8]
                "991" -> return hundreds[8] + " and " + tens[8] + units[0]
                "992" -> return hundreds[8] + " and " + tens[8] + units[1]
                "993" -> return hundreds[8] + " and " + tens[8] + units[2]
                "994" -> return hundreds[8] + " and " + tens[8] + units[3]
                "995" -> return hundreds[8] + " and " + tens[8] + units[4]
                "996" -> return hundreds[8] + " and " + tens[8] + units[5]
                "997" -> return hundreds[8] + " and " + tens[8] + units[6]
                "998" -> return hundreds[8] + " and " + tens[8] + units[7]
                "999" -> return hundreds[8] + " and " + tens[8] + units[8]
            }
        } else {
            return thousand[0]
        }
    }
}
